Fix bug with wrong values in parsed kubernetes yaml keys
In some cases keys from kubernetes and/or run_on_dockers objects get mixed up.

for example namespace will get a false or true value instead of the
actual namespace specifyed in kubernetes key.

Example for such Error from a real run:

ERROR: parallel task failed with msg: java.lang.RuntimeException: Failed to parse yaml: "
spec:
  containers:
    - name: docker
      resources:
        limits: {memory: 8Gi, cpu: 8000m, mellanox.com/sriov_cx6dx_p1: 1}
        requests: {memory: 8Gi, cpu: 8000m, mellanox.com/sriov_cx6dx_p1: 1}
  tolerations: xlio-ci
"

Note the mixed variables, 'tolerations' (which is empty value in the yaml
file) will be assigned to the namespace value from lubernetes key (xlio-ci in this example)

This is caused because one of the variables in getConfigVal function
which is being called in every run_k8s is global ad not local which is
causing this variable to get wrong value from another parallel process
running at same time.

The fix is simple and is to add def for item variable to make it local.

Signed-off-by: Daniel Pressler <danielpr@nvidia.com>